# Generated by Django 5.1.2 on 2024-11-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=2048)),
                ('short_reviwe', models.CharField(max_length=2048)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(default='https://images.pexels.com/photos/886521/pexels-photo-886521.jpeg', upload_to='images/')),
            ],
        ),
    ]
